open_file = open('ddg_alanine_scan_34.err')